package:
  name: m4
  version: "1.4.17"

source:
  fn: m4-1.4.17.tar.xz
  url: http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.xz  # [linux]
  sha1: 74ad71fa100ec8c13bc715082757eb9ab1e4bbb0

build:
  number: 0

test:
  commands:
    - exit $(test -f ${PREFIX}/bin/m4)
    - m4 --help
