package:
  name: cairo
  version: 1.12.18

source:
  fn: cairo-1.12.18.tar.xz
  url: http://cairographics.org/releases/cairo-1.12.18.tar.xz
  md5: 8e4ff32b82c3b39387eb6f5c59ef848e

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - freetype
    - fontconfig
    - libpng
    - pixman
    - zlib
  run:
    - freetype
    - fontconfig
    - libpng ==1.2.52
    - pixman
    - zlib

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libcairo.so)
