package:
  name: texinfo 
  version: "5.2"

source:
  fn: texinfo-5.2.tar.xz
  url: http://ftp.gnu.org/gnu/texinfo/texinfo-5.2.tar.xz  # [linux]
  sha1: fbbc35c5857d11d1164c8445c78b66ad6d472072

build:
  number: 0
  detect_binary_files_with_prefix: true

test:
  commands:
    - exit $(test -f ${PREFIX}/bin/makeinfo)
    - makeinfo --help
