package:
    name: udunits
    version: 2.2.17

source:
    fn: v2.2.17.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.17.tar.gz  # [linux]
    sha1: 3dfb7b1f18e21ac5366127778bbfd50ab5b7cf0a

build:
    number: 0
    detect_binary_files_with_prefix: true

requirements:
  build:
    - m4
    - autoconf
    - automake
    - libtool
    - texinfo

test:
    commands:
        - udunits2 -h
        - udunits2 -H meter -W miles
