package:
  name: pixman 
  version: "0.32.6"

source:
  fn: pixman-0.32.6.tar.gz
  url: http://cairographics.org/releases/pixman-0.32.6.tar.gz  # [linux]
  sha1: 8791343cbf6d99451f4d08e8209d6ac11bf96df2

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - zlib
    - libpng ==1.2.52
  run:
    - zlib
    - libpng ==1.2.52

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libpixman-1.so)
