package:
  name: zlib
  version: "1.2.8"

source:
  fn: zlib-1.2.8.tar.xz
  url: http://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.xz  # [linux]
  sha1: b598beb7acc96347cbd1020b71aef7871d374677 

build:
  number: 0

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libz.so.1.2.8)
